image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - npm test

deploy:
  stage: deploy
  environment:
    name: production
    url: https://example.com
  script:
    - npm run deploy